USE bdDeli;

ALTER TABLE sales
    ADD COLUMN arequipe BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN powdered_milk BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN raisins BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN toppings_total DECIMAL(12, 2) NOT NULL DEFAULT 0;