USE bdDeli;

ALTER TABLE sales
ADD COLUMN arequipe INT NOT NULL DEFAULT 0,
ADD COLUMN powdered_milk INT NOT NULL DEFAULT 0,
ADD COLUMN raisins INT NOT NULL DEFAULT 0,
ADD COLUMN toppings_total DECIMAL(12, 2) NOT NULL DEFAULT 0;